version: '3'
services:
    influxdb:
        image: influxdb
        ports:
        - "8086:8086"
        volumes:
        - "influxdb_data:/var/lib/influxdb"
    datalake:
        image: aiotesdocker/datalayer-datalake-ids
        ports:
        - "4567:4567"
        environment:
          HOST_INFLUXDB: 172.17.0.1
          PORT_INFLUXDB: 8086
        links:
        - influxdb
volumes:
  influxdb_data: